#ifndef CAT_COMMAND_H
	#define CAT_COMMAND_H

/** \file
 * This file is the interface to the cat command.
 */

#include "NexShell.h"

#define CAT_HELP_TEXT \
\
"Usage: " CAT_COMMAND_NAME " [OPTION]... [FILE]..." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Read contents of a file." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Display the content of file on the standard output." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Options:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"-E        display $ at end of each line" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"-n        number all output lines" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"-T        display TAB characters as ^I" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"-v        use ^ and M- notation, except for LFD and TAB" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Examples:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB CAT_COMMAND_NAME " /a-folder/file-to-get-the-text-of" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB CAT_COMMAND_NAME " -EnT ../a-folder/file-to-get-the-text-of another-file-to-read" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE

 /*!
 * @union READ_OPTIONS
 *
 * @brief This union holds all the data for determining the options the user specified with the cat command.
 *
 * @param BYTE Value - The 8 bit value of the option bits to address in one read/write.
 *
 * @param unsigned int ShowLineEnds - If this bit is set the line ends will have a $.
 * @param unsigned int NumberAllLines - If this bit is set all lines will be numbered.
 * @param unsigned int SupressRepeativeEmptyLines  - Unsupported.
 * @param unsigned int ShowTabs - If this bit is set the tabs will be shown with ^I.
 * @param unsigned int ShowControlCharacters - If this bit is set non printable characters will be shown.
 * @param unsigned int CarriageReturnPresent - Internal use for keeping track of \r.
 * @param unsigned int Reserved - Reserved for future use.
 *
 * @details This data strucuture is used to set any flag bits of options that were parsed
 * out from the user arguments for the cat command.
 */
typedef union
{
	BYTE Value;

	struct
	{
		unsigned int ShowLineEnds : 1;					// -E
		unsigned int NumberAllLines : 1;				// -n
		unsigned int SupressRepeativeEmptyLines : 1;	// -s (unsupported for now)
		unsigned int ShowTabs : 1;						// -T
		unsigned int ShowControlCharacters : 1;			// -v
		unsigned int CarriageReturnPresent : 1;			// Internal Use
		unsigned int Reserved : 2;
	}BITS;
}READ_OPTIONS;

/*!
* @struct READ_INFO
*
* @brief This data structure holds all the data for the options specified when using the cat command.
*
* @param BYTE Value - The 8 bit value of the option bits to address in one read/write.
*
* @param READ_OPTIONS ReadOptions - This holds the options bits that were parsed out from the user args to the cat command.
* @param UINT32 LineNumber - The current line number the cat command is on in a file it is reading.
*
* @details This data strucuture is used to set any flag bits of options that were parsed
* out from the user arguments for the cat command.  It also holds state data of the current
* cat operation on a file.
*/
typedef struct
{
	READ_OPTIONS ReadOptions;
	UINT32 LineNumber;
}READ_INFO;

/*!
 * @brief Executes the cat command with the given arguments.
 *
 * @param[in] char* Args[] - An array of string arguments to process.
 * 
 * @param[in] UINT32 NumberOfArgs - The number of valid arguments present in char *Args[].
 * 
 * @param[in,out] PIPE* OutputStream - The stream that will get written to with any output.
 *
 * @return SHELL_RESULT - The outcome of the operation.
 *
 * @details
 * This function is what is eventually called when the user issues the cat command through
 * the shell.  Any output that is generated by the cat command is written to the OutputStream.
 */
SHELL_RESULT catCommandExecuteMethod(char* Args[], UINT32 NumberOfArgs, PIPE* OutputStream);

#endif // end of CAT_COMMAND_H
