#ifndef CD_COMMAND_H
	#define CD_COMMAND_H

/** \file
 * This file is the interface to the cd command.
 */

#include "NexShell.h"

#define CD_HELP_TEXT \
\
"Usage: " CD_COMMAND_NAME " [dir]" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Change the shell working directory." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Changes the current directory to DIR.  If .. is used this denotes the parent directory." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "A period '.' denotes the current working directory ./ (current_working_directory)."  SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "A " SHELL_HOME_DIRECTORY_CHARACTER_STRING " goes to the home directory.  A - goes to the prior directory used in the last " CD_COMMAND_NAME "."  SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Examples:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB CD_COMMAND_NAME " /folder-1/folder2" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB CD_COMMAND_NAME " ../" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB CD_COMMAND_NAME " " SHELL_HOME_DIRECTORY_CHARACTER_STRING SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB CD_COMMAND_NAME " -" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE

 /*!
  * @brief Initializes the cd command.
  * 
  * @return SHELL_RESULT - The outcome of the operation.
  *
  * @details
  * This function is called by NexShellInit().  It is only used when EXTENDED_CD_SUPPORT
  * inside of NexShellConfig.h is set to a 1.  This method should not be called by the user.
  */
SHELL_RESULT cdInit(void);

/*!
 * @brief Main entry point for the cd command in the shell.
 *
 * @param[in] char* Args[] - An array of string arguments to process.
 *
 * @param[in] UINT32 NumberOfArgs - The number of valid arguments present in char *Args[].
 *
 * @param[in,out] PIPE* OutputStream - The stream that will get written to with any output.
 *
 * @return SHELL_RESULT - The outcome of the operation.
 *
 * @details
 * This function is what is eventually called when the user issues the cd command through
 * the shell.  Any output that is generated by the cd command is written to the OutputStream.
 */
SHELL_RESULT cdCommandExecuteMethod(char* Args[], UINT32 NumberOfArgs, PIPE* OutputStream);

#endif // end of #ifndef CD_COMMAND_H
