#ifndef CLEAR_COMMAND_H
	#define CLEAR_COMMAND_H

/** \file
 * This file is the interface to the clear command.
 */

#include "NexShell.h"

#define CLEAR_HELP_TEXT \
\
"Usage: " CLEAR_COMMAND_NAME SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Clear the terminal screen." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "This command will clear the terminal screen." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "This will also reset the cursor position to 0, 0." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Example:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB CLEAR_COMMAND_NAME SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE

/*!
 * @brief
 *
 * @param[in] char* Args[] - An array of string arguments to process.
 *
 * @param[in] UINT32 NumberOfArgs - The number of valid arguments present in char *Args[].
 *
 * @param[in,out] PIPE* OutputStream - The stream that will get written to with any output.
 *
 * @return SHELL_RESULT - The outcome of the operation.
 *
 * @details
 * This function is what is eventually called when the user issues the clear command through
 * the shell.  Any output that is generated by the clear command is written to the OutputStream.
 */
SHELL_RESULT clearCommandExecuteMethod(char* Args[], UINT32 NumberOfArgs, PIPE* OutputStream);

#endif // end of CLEAR_COMMAND_H
