#ifndef LS_COMMAND_H
	#define LS_COMMAND_H

#include "../NanoShell.h"

#if (EXTENDED_LS_SUPPORT == 1)
	#define LS_HELP_TEXT \
	\
	LS_COMMAND_NAME ": " LS_COMMAND_NAME " [dir]" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "List a directories contents." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "Lists the specified directories contents.  If no argument is supplied the working directory is used." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "Examples:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB SHELL_TAB LS_COMMAND_NAME SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB SHELL_TAB LS_COMMAND_NAME " /folder-1/folder-2" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB SHELL_TAB LS_COMMAND_NAME " ../" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE
#else
	#define LS_HELP_TEXT \
	\
	LS_COMMAND_NAME ": " LS_COMMAND_NAME " [dir]" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "List a directories contents." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "Lists the specified directories contents.  If no argument is supplied the working directory is used." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "Examples:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB SHELL_TAB LS_COMMAND_NAME SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB SHELL_TAB LS_COMMAND_NAME " /folder-1/folder-2" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB SHELL_TAB LS_COMMAND_NAME " ../" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE
#endif // end of #if (EXTENDED_CD_SUPPORT == 1)

SHELL_RESULT lsCommandExecuteMethod(char* Args[], UINT32 NumberOfArgs, GENERIC_BUFFER* Buffer);

#endif // end of LS_COMMAND_H