#ifndef MKDIR_COMMAND_H
	#define MKDIR_COMMAND_H

/** \file
 * This file is the interface to the mkdir command.
 */

#include "NexShell.h"

#define MKDIR_HELP_TEXT \
\
"Usage: " MKDIR_COMMAND_NAME " [OPTION]... DIRECTORY..." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Create the DIRECTORY(ies), if they do not already exist." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Options:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"-m        Set file mode, bit values can logically or'ed." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB SHELL_TAB "        Valid bit values and their meanings are as follows:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB SHELL_TAB"          1 = Read Only" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB SHELL_TAB"          2 = Hidden" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB SHELL_TAB"          4 = System" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB SHELL_TAB"          32 = Archive" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"-p        no error if existing, make parent directories as needed." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"          Their file modes would be unaffected by any - m option." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Examples:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB MKDIR_COMMAND_NAME " -p ./a-folder/another-folder" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB MKDIR_COMMAND_NAME " -m5 directory-to-add" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE

 /*!
 * @union MKDIR_OPTIONS
 * 
 * @brief This data structure holds all the enable bits for options with the mkdir command.
 * 
 * @param BYTE Value - The 8 bit value of the option bits to address in one read/write.
 * 
 * @param unsigned int AllowParentDirectoryCreation - If set, a folder with a parent folder(s) can be created.
 * @param unsigned int Mode - If set, the mode bits are present in the \ref MKDIR_OPTIONS_DATA.
 * @param unsigned int Reserved - Reserved for furture use.
 * 
 * @details This data strucuture is used to set any flag bits of options that were parsed
 * out from the user arguments for the mkdir command.
 */
typedef union
{
	BYTE Value;

	struct
	{
		unsigned int AllowParentDirectoryCreation : 1;
		unsigned int Mode : 1;
		unsigned int Reserved : 6;
	}Bits;
}MKDIR_OPTIONS;

/*!
* @struct MKDIR_OPTIONS_DATA
*
* @brief This struct holds all the options for creating a new folder.
*
* @param MKDIR_OPTIONS Options - The various options enable bits that go with folder creation.
*
* @param BYTE FolderCreateMode - The mode bits which will be set in the folder at creation.
*
* @details
* This data structure is used when parsing the mkdir command.  The appropriate bits are set
* within the struct and then passed to the actual portion of code that makes the directory.
*/
typedef struct
{
	MKDIR_OPTIONS Options;
	BYTE FolderCreateMode;
}MKDIR_OPTIONS_DATA;

/*!
 * @brief Main entry point for the mkdir command in the shell.
 *
 * @param[in] char* Args[] - An array of string arguments to process.
 *
 * @param[in] UINT32 NumberOfArgs - The number of valid arguments present in char *Args[].
 *
 * @param[in,out] PIPE* OutputStream - The stream that will get written to with any output.
 *
 * @return SHELL_RESULT - The outcome of the operation.
 *
 * @details
 * This function is what is eventually called when the user issues the mkdir command through
 * the shell.  Any output that is generated by the mkdir command is written to the OutputStream.
 */
SHELL_RESULT mkdirCommandExecuteMethod(char* Args[], UINT32 NumberOfArgs, PIPE* OutputStream);

#endif // end of MKDIR_COMMAND_H
