#ifndef SHUTDOWN_COMMAND_H
	#define SHUTDOWN_COMMAND_H

/** \file
 * This file is the interface to the shutdown command.
 */

#include "NexShell.h"

#define SHUTDOWN_HELP_TEXT \
\
"Usage: " SHUTDOWN_COMMAND_NAME " [OPTION]..."SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Arranges for the system to be brought down in a safe way." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Only one argument should be sent to the " SHUTDOWN_COMMAND_NAME " command." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "If no arguments are supplied it is equivalent to -P." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Options:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"-H        requests that the system be halted after it has been brought down" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"-P        requests that the system be powered off after it has been brought down" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"-r        requests that the system be rebooted after it has been brought down" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Examples:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB SHUTDOWN_COMMAND_NAME SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB SHUTDOWN_COMMAND_NAME " -r" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE

/*!
 * @brief
 *
 * @param[in] char* Args[] - An array of string arguments to process.
 *
 * @param[in] UINT32 NumberOfArgs - The number of valid arguments present in char *Args[].
 *
 * @param[in,out] PIPE* OutputStream - The stream that will get written to with any output.
 *
 * @return SHELL_RESULT - The outcome of the operation.
 *
 * @details
 * This function is what is eventually called when the user issues the shutdown command through
 * the shell.  Any output that is generated by the shutdown command is written to the OutputStream.
 */
SHELL_RESULT shutdownCommandExecuteMethod(char* Args[], UINT32 NumberOfArgs, PIPE* OutputStream);

#endif // end of SHUTDOWN_COMMAND_H
