#ifndef SHUTDOWN_COMMAND_H
	#define SHUTDOWN_COMMAND_H

#include "NexShell.h"

#define SHUTDOWN_HELP_TEXT \
\
SHUTDOWN_COMMAND_NAME ": " SHUTDOWN_COMMAND_NAME " [-HPr]"SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Arranges for the system to be brought down in a safe way." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Only one argument should be sent to the " SHUTDOWN_COMMAND_NAME " command." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "If no arguments are supplied it is equivalent to -P." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Options:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"-H        requests that the system be halted after it has been brought down" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"-P        requests that the system be powered off after it has been brought down" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB"-r        requests that the system be rebooted after it has been brought down" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB "Examples:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB SHUTDOWN_COMMAND_NAME SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_TAB SHELL_TAB SHUTDOWN_COMMAND_NAME " -r" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
SHELL_DEFAULT_END_OF_LINE_SEQUENCE

SHELL_RESULT shutdownCommandExecuteMethod(char* Args[], UINT32 NumberOfArgs, GENERIC_BUFFER* OutputStream);

#endif // end of SHUTDOWN_COMMAND_H